#pragma once

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP16
#define I2C1_SCL_PIN GP25
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_OLED_ENABLE
#define RGB_MATRIX_SPLIT { 33, 33 }
#define SPLIT_TRANSACTION_IDS_KB JOYSTICK_SYNC
#define MOUSE_EXTENDED_REPORT