#pragma once

#define I2C_DRIVER I2CD0
#define I2C1_SDA_PIN GP16
#define I2C1_SCL_PIN GP25
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_OLED_ENABLE
#define RGB_MATRIX_SPLIT { 33, 33 }
#define SPLIT_TRANSACTION_IDS_KB POINTING_DEVICE_SYNC

#define USB_SUSPEND_WAKEUP_DELAY 1000
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_USB_DETECT
#define SPLIT_USB_TIMEOUT 2000